# Setup
title: Blog
description: oss
url: https://jiseok01.github.io
avatar: https://cdn.pixabay.com/photo/2020/11/25/14/14/cat-5775895__340.jpg
paginate: 5
permalink: pretty
cover_image: https://cdn.pixabay.com/photo/2022/03/24/14/42/animal-7089224__340.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: jiseok
  card: summary
logo: logo.png
social:
  name: jiseok
  links:
    - https://twitter.com/
    - https://github.com/jiseok01
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: jiseok
  url: https://github.com/jiseok01/
  email: 
